<!--
 MIT License

 Copyright (c) 2025 The University of Texas MD Anderson Cancer Center

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the 'Software'), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
-->

## Polar metabolite profiling by IC-MS Non-Targeted

To determine the relative abundance of polar metabolites, extracts were prepared and analyzed by ion chromatography-mass spectrometry (IC-MS). Metabolites were extracted using ice-cold 0.1% ammonium hydroxide in methanol:water = 80:20. Extracts were centrifuged at 17,000 gfor 5 min at 4°C, and supernatants were transferred to clean tubes, followed by evaporation to dryness under nitrogen. Dried extracts were reconstituted in 200 µL deionized water, and 10 µL was injected for analysis. IC mobile phase A (MPA; weak) was water, and mobile phase B (MPB; strong) was water containing 100 mM KOH. A Thermo Dionex ICS-6000+ system included a Thermo IonPac AS11 column (4 µm particle size, 250 x 2 mm) with column compartment set at 35°C. The autosampler tray was chilled to 4°C. The mobile phase flow rate was 360 µL/min, and the gradient elution program was: 0-2 min, 1% MPB; 2-25 min, 1-40% MPB; 25-39 min, 40-100% MPB; 39-50 min, 100% MPB; 50-50.5, 100-1% MPB. The total run time was 55 min. To improve desolvation for better sensitivity, methanol was delivered by an external pump and combined with the eluent via a low dead volume mixing tee. Data were acquired using a Thermo Fisher Scientific Orbitrap IQ-X Tribrid Mass Spectrometer under ESI negative ionization mode at a resolution of 240,000 with a scan range of 70-800 m/z.  All raw data files were imported into Skyline/Thermo Trace Finder 5.1 software for processing. The relative abundance (peak area) of each metabolite was normalized by total peak intensity.

