<!--
 MIT License

 Copyright (c) 2025 The University of Texas MD Anderson Cancer Center

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the 'Software'), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
-->

## Time Series &Delta;AUC

<style>
  sup {
    /* to prevent the superscripts from being italicized (because the DataTables superscripts are not italicized) */
    font-style: normal;
  }
  table.aucdefs td { /* using table instead of list to better control vertical alignment */
    padding-left: 10px;
  }
  table.aucdefs {
    margin-left: 10px;
    margin-bottom: 10px;
  }

</style>

This table allows the user to rank-sort significantly modulated metabolites based on areas under the
curve (AUC). Areas are estimated using the splines method. The dropdown can be used to
change groups to compare. The table can be downloaded from the buttons above the table.

The various table quantities are calculated as follows:

<table class="aucdefs">
  <tr>
    <td><b>&Delta;AUC</b></td>
    <td>2<sup>nd</sup>AUC - 1<sup>st</sup>AUC</td>
  </tr>
  <tr>
    <td><b>1<sup>st</sup>AUC</b></td>
    <td>Area under the curve of the first group</td>
  </tr>
  <tr>
    <td><b>2<sup>nd</sup>AUC</b></td>
    <td>Area under the curve of the second group</td>
  </tr>
  <tr>
    <td><b>&percnt;&Delta;AUC</b></td>
    <td>&Delta;AUC / 1<sup>st</sup>AUC x 100</td>
  </tr>
  <tr>
    <td><b>propAUC</b></td>
    <td>+AUC / (+AUC + -AUC) x 100</td>
  </tr>
  <tr>
    <td><b>+AUC</b></td>
    <td>Area under 1<sup>st</sup>(<i>time</i>) - 2<sup>nd</sup>(<i>time</i>), defined only when 1<sup>st</sup>(<i>time</i>) > 2<sup>nd</sup>(<i>time</i>)</td>
  </tr>
  <tr>
    <td><b>-AUC</b></td>
    <td>Area under 1<sup>st</sup>(<i>time</i>) - 2<sup>nd</sup>(<i>time</i>), defined only when 1<sup>st</sup>(<i>time</i>) < 2<sup>nd</sup>(<i>time</i>)</td>
  </tr>
</table>

```{r, results='asis', echo=FALSE, warning=FALSE, message=FALSE, fig.align="center"}
deltaAUCnames <- c()
deltaAUCall <- list()
for (i in 1:length(aucfiles)) {
  deltaAUCFile <- paste(reportFolderPath, aucfiles[i], sep="")
  deltaAUC <- read.csv(deltaAUCFile, header = TRUE, row.names = 1)
  deltaAUCnames <- c(deltaAUCnames, gsub(".csv", "", aucfiles[i]))
  deltaAUCall[[i]] <- deltaAUC
}
names(deltaAUCall) <- deltaAUCnames
df_to_js(deltaAUCall, var_name="deltaAUCall")
```

<div id="aucDiv"></div> <!--div used by js/Smooth.js -->
<script>calcDeltaAUC();</script>
