<!--
 MIT License

 Copyright (c) 2025 The University of Texas MD Anderson Cancer Center

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the 'Software'), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
-->

## Volcano Plot

The volcano plot provides differentially modulated metabolites of pairwise comparisons by combining
log<sub>2</sub>(Fold change) and -log<sub>10</sub>(p-value) on to a single graph. This plot allows the user
to comprehensively identify significantly modulated metabolites based on either biological significance,
statistical significance, or both. The volcano plot is also highly dynamic. You can use the dropdown
buttons to choose the covariate, groups to compare, and additional comparison parameters in the
'limit comparison' dropdown. The p-value and fold change cutoffs can be changed via either the text boxes or
sliders. The data can also be downloaded from the Data matrix tab.

<div id='flex-container-volcano'>
<div id='volcanoControlDiv'>
  <label for='covarselect'>Covariate:</label>
    <select id='covarselect'></select>
    <br>
  <label for='groupselect1'>Select groups to compare:</label>
    <select id='groupselect1'></select>
    <button id='swapDropdownValues'>
      <svg xmlns="http://www.w3.org/2000/svg" height="12" width="10.5" viewBox="0 0 448 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M438.6 150.6c12.5-12.5 12.5-32.8 0-45.3l-96-96c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L338.7 96 32 96C14.3 96 0 110.3 0 128s14.3 32 32 32l306.7 0-41.4 41.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l96-96zm-333.3 352c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.3 416 416 416c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0 41.4-41.4c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-96 96c-12.5 12.5-12.5 32.8 0 45.3l96 96z"/></svg>
    </button>
    <select id='groupselect2'></select>
    <br>
  <label for='groupselectlimit' id='selectlimitlabel'>Limit comparision in:</label>
    <select id='groupselectlimit'></select>
    <br>
  <div id="slidersForVolcanoPlot">
   <label for='foldChangeCut'>log<sub>2</sub>(Fold Change): &gt; </label>
    <input type='text' id='foldChangeCut' value="1.5">
    <div id='foldchangeSlider'></div>
   <label for='pvalueCut'>-log<sub>10</sub>(p-value): &gt; </label>
    <input type='text' id='pvalueCut' value="1.3">
    <div id='pvalueSlider'></div>
   <br>
   <button id='resetVolcano'>Reset Sliders</button>
  </div>
</div>
<div id='volcanoDiv'></div>
</div>

<div id = "volcanoDataTableDiv">
The log<sub>2</sub> fold change is the log<sub>2</sub> of the ratio between the average values across samples of
two conditions.'adjusted pvalue' represent the p-value of each treatment group adjusted across other pairwise comparison.

<table id='volcanoDataTable'></table>
</div>

<style>
#foldchangeSlider {
  width: 90%;
  margin-left: 5%;
  margin-right: 5%;
  margin-top: 10px;
  margin-bottom: 10px;
}
#pvalueSlider {
  width: 90%;
  margin-left: 5%;
  margin-right: 5%;
  margin-top: 10px;
  margin-bottom: 10px;
}
#pvalueCut {
  width: 5em;
  margin-left: .5em;
}
#foldChangeCut {
  width: 5em;
  margin-left: .5em;
}
#flex-container-volcano {
  display: flex;
}
#volcanoControlDiv, #volcanoDiv {
  flex: 1;
  padding: 20px;
}
#volcanoControlDiv {
  padding-top: 40px;
  padding-right: 50px;
}
</style>



